# Site settings
title: George's Code Thoughts
header-img: img/home-bg.jpg
email: sunwinner3@gmail.com
description: "Yet another tech blog!"
baseurl: ""
url: "http://codethoughts.info"
twitter_username: kui_sun
github_username: puffsun
facebook_username: kui.sun.71

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 9
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
# Generate sitemap automatically
gems:
  - jekyll-sitemap

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# # Default templates for posts and pages
# # Found in _templates/
post_layout: post
page_layout: page

# # Format titles with titlecase?
titlecase: true
#
# # Change default template file (in _templates/)
# post_template: post
# page_template: page
# draft_template: draft
